de:
  contentDir: content/de
  languageCode: de-DE
  languageName: Deutsch
  weight: 2
en:
  contentDir: content/en
  languageCode: en-EN
  languageName: English
  weight: 1
fr:
  contentDir: content/fr
  languageCode: fr-FR
  languageName: Français
  weight: 3
ja:
  contentDir: content/ja
  languageCode: ja-JA
  languageName: 日本語
  weight: 4
